version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=profiles
      - POSTGRES_USER=profiles
      - POSTGRES_DB=profiles
    volumes:
      - './postgres_data:/var/lib/postgresql/data'
    
    ports:
      - '5432:5432'